### ISSUE TITLE
PaperTrail regression in version 7: Models fail to save in unimplemented delegation that overrides column

### ISSUE THREAD

**Issue by AlexEvanczuk** [airblade/paper_trail#1012]
## Problem
I have a model that has some attribute X.  I also have that model delegate X to some other polymorphic model A.  That model does not implement X in some cases.  This breaks paper trail, because paper trail uses the model attributes to decide what changed.
`/Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-8.0.1/lib/paper_trail/record_trail.rb`
```ruby
    def changes
      notable_changes = changes_in_latest_version.delete_if { |k, _v|
        !notably_changed.include?(k)
      }
      AttributeSerializers::ObjectChangesAttribute.
        new(@record.class).
        serialize(notable_changes)
      notable_changes.to_hash
    end

    # @api private
    def attribute_in_previous_version(attr_name)
      if @in_after_callback && RAILS_GTE_5_1
        @record.attribute_before_last_save(attr_name.to_s)
      else
        @record.attribute_was(attr_name.to_s)
      end
    end
```
This starts to go into: `ActiveModel::Dirty` and `ActiveRecord::Dirty`
`/Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activemodel-4.2.7.1/lib/active_model/dirty.rb`
```
      # Handle <tt>*_change</tt> for +method_missing+.
      def attribute_change(attr)
        [changed_attributes[attr], __send__(attr)] if attribute_changed?(attr)
      end
```

Basically it they send the attribute, which uses the delegated method.

## Possible Solution
I'm not exactly sure who would fix this.  Maybe `ActiveRecord` should properly handle the method missing case, or it should use `read_attribute` rather than `send`.
Similarly, we weren't seeing this problem until we upgraded from 5.2.  If you change the paper trail version to 5 below, the script runs without error.

## Reproduction
```ruby
# Use this template to report PaperTrail bugs.
# Please include only the minimum code necessary to reproduce your issue.
require "bundler/inline"

# STEP ONE: What versions are you using?
gemfile(true) do
  ruby "2.3.5"
  source "https://rubygems.org"
  gem "activerecord", "4.2.7.1"
  gem "minitest", "5.10.3"
  gem "paper_trail", "7", require: false
  gem "sqlite3"
  gem 'pry-byebug', '~> 3.3'
end

require "active_record"
require "logger"

# Please use sqlite for your bug reports, if possible.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil
ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :super_user_details, force: true do |t|
    t.text :company_name, null: false
    t.text :level, null: false
  end

  create_table :regular_user_details, force: true do |t|
    t.text :company_name, null: false
  end

  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.text :level
    t.references :user_detail, polymorphic: true, index: true, null: false
  end

  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.integer :transaction_id
    t.datetime :created_at
  end

  add_index :versions, %i[item_type item_id]
  add_index :versions, [:transaction_id]

  create_table :version_associations do |t|
    t.integer  :version_id
    t.string   :foreign_key_name, null: false
    t.integer  :foreign_key_id
  end
  add_index :version_associations, [:version_id]
  add_index :version_associations, %i[foreign_key_name foreign_key_id],
    name: "index_version_associations_on_foreign_key"
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.raise_in_transactional_callbacks = true
# Rails::Application::Configuration.active_record.raise_in_transactional_callbacks = true
require "paper_trail/config"

# STEP THREE: Configure PaperTrail as you would in your initializer
PaperTrail::Config.instance.track_associations = false

require "paper_trail"

# STEP FOUR: Define your AR models here.
class User < ActiveRecord::Base
  has_paper_trail
  belongs_to :user_detail, polymorphic: true, inverse_of: :user, autosave: true, dependent: :destroy
  delegate :company_name, :level, to: :user_detail
end

class SuperUserDetails < ActiveRecord::Base
  has_paper_trail
  has_one :user, as: :user_detail, autosave: false, inverse_of: :user_detail
end

class RegularUserDetails < ActiveRecord::Base
  has_paper_trail
  has_one :user, as: :user_detail, autosave: false, inverse_of: :user_detail
end
require 'pry'
regular_user_details = RegularUserDetails.create(company_name: 'Big Corp Inc.')
user = User.create(first_name: 'Fred', user_detail: regular_user_details)
user.update_column(:level, :a)
puts user

user.first_name = 'Other name'
user.save!

# STEP SIX: Run this script using `ruby reproduce.rb`
```
## Output with PaperTrail major version 7
```
~/workspace/reproduce_papertrail_issue - $ ruby /Users/alex.evanczuk/workspace/reproduce_papertrail_issue/reproduce.rb
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using json 1.8.6
Using minitest 5.10.3
Using thread_safe 0.3.6
Using builder 3.2.3
Using arel 6.0.4
Using bundler 1.15.4
Using byebug 9.1.0
Using coderay 1.1.2
Using method_source 0.9.0
Using request_store 1.3.2
Using sqlite3 1.3.13
Using i18n 0.9.1
Using tzinfo 1.2.4
Using pry 0.11.3
Using activesupport 4.2.7.1
Using pry-byebug 3.5.1
Using activemodel 4.2.7.1
Using activerecord 4.2.7.1
Using paper_trail 7.0.0
-- create_table(:super_user_details, {:force=>true})
   -> 0.0030s
-- create_table(:regular_user_details, {:force=>true})
   -> 0.0003s
-- create_table(:users, {:force=>true})
   -> 0.0106s
-- create_table(:versions)
   -> 0.0003s
-- add_index(:versions, [:item_type, :item_id])
   -> 0.0002s
-- add_index(:versions, [:transaction_id])
   -> 0.0003s
-- create_table(:version_associations)
   -> 0.0002s
-- add_index(:version_associations, [:version_id])
   -> 0.0002s
-- add_index(:version_associations, [:foreign_key_name, :foreign_key_id], {:name=>"index_version_associations_on_foreign_key"})
   -> 0.0003s
D, [2017-11-30T16:09:06.740636 #93429] DEBUG -- :    (0.0ms)  begin transaction
D, [2017-11-30T16:09:06.744038 #93429] DEBUG -- :   SQL (0.1ms)  INSERT INTO "regular_user_details" ("company_name") VALUES (?)  [["company_name", "Big Corp Inc."]]
D, [2017-11-30T16:09:06.757441 #93429] DEBUG -- :   SQL (0.1ms)  INSERT INTO "versions" ("event", "object_changes", "item_id", "item_type", "created_at") VALUES (?, ?, ?, ?, ?)  [["event", "create"], ["object_changes", "---\ncompany_name:\n- \n- Big Corp Inc.\nid:\n- \n- 1\n"], ["item_id", 1], ["item_type", "RegularUserDetails"], ["created_at", "2017-12-01 00:09:06.756861"]]
D, [2017-11-30T16:09:06.761273 #93429] DEBUG -- :   SQL (0.1ms)  UPDATE "versions" SET "transaction_id" = ? WHERE "versions"."id" = ?  [["transaction_id", 1], ["id", 1]]
D, [2017-11-30T16:09:06.761814 #93429] DEBUG -- :    (0.1ms)  commit transaction
D, [2017-11-30T16:09:06.767781 #93429] DEBUG -- :    (0.0ms)  begin transaction
D, [2017-11-30T16:09:06.768664 #93429] DEBUG -- :   SQL (0.1ms)  INSERT INTO "users" ("first_name", "user_detail_id", "user_detail_type") VALUES (?, ?, ?)  [["first_name", "Fred"], ["user_detail_id", 1], ["user_detail_type", "RegularUserDetails"]]
D, [2017-11-30T16:09:06.771043 #93429] DEBUG -- :   SQL (0.1ms)  INSERT INTO "versions" ("event", "object_changes", "item_id", "item_type", "created_at") VALUES (?, ?, ?, ?, ?)  [["event", "create"], ["object_changes", "---\nfirst_name:\n- \n- Fred\nuser_detail_id:\n- \n- 1\nuser_detail_type:\n- \n- RegularUserDetails\nid:\n- \n- 1\n"], ["item_id", 1], ["item_type", "User"], ["created_at", "2017-12-01 00:09:06.770614"]]
D, [2017-11-30T16:09:06.772401 #93429] DEBUG -- :   SQL (0.1ms)  UPDATE "versions" SET "transaction_id" = ? WHERE "versions"."id" = ?  [["transaction_id", 2], ["id", 2]]
D, [2017-11-30T16:09:06.772760 #93429] DEBUG -- :    (0.0ms)  commit transaction
D, [2017-11-30T16:09:06.773222 #93429] DEBUG -- :   SQL (0.1ms)  UPDATE "users" SET "level" = 'a' WHERE "users"."id" = ?  [["id", 1]]
#<User:0x00007f7f8d2a1e58>
D, [2017-11-30T16:09:06.773411 #93429] DEBUG -- :    (0.0ms)  begin transaction
D, [2017-11-30T16:09:06.774046 #93429] DEBUG -- :   SQL (0.1ms)  UPDATE "users" SET "first_name" = ? WHERE "users"."id" = ?  [["first_name", "Other name"], ["id", 1]]
D, [2017-11-30T16:09:06.774453 #93429] DEBUG -- :    (0.0ms)  rollback transaction
/Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activemodel-4.2.7.1/lib/active_model/attribute_methods.rb:433:in `method_missing': undefined method `level' for #<RegularUserDetails id: 1, company_name: "Big Corp Inc."> (NoMethodError)
	from /Users/alex.evanczuk/workspace/reproduce_papertrail_issue/reproduce.rb:76:in `level'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activemodel-4.2.7.1/lib/active_model/dirty.rb:185:in `attribute_was'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/record_trail.rb:479:in `attribute_in_previous_version'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/record_trail.rb:41:in `block in attributes_before_change'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/record_trail.rb:39:in `each'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/record_trail.rb:39:in `map'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/record_trail.rb:39:in `attributes_before_change'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/record_trail.rb:190:in `object_attrs_for_paper_trail'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/record_trail.rb:313:in `recordable_object'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/record_trail.rb:290:in `data_for_update'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/record_trail.rb:273:in `record_update'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/paper_trail-7.0.0/lib/paper_trail/model_config.rb:66:in `block in on_update'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:448:in `instance_exec'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:448:in `block in make_lambda'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `block in call'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `each'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `call'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:310:in `_update_record'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:70:in `_update_record'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:142:in `save!'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:43:in `save!'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `block in save!'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /Users/alex.evanczuk/.gem/ruby/2.3.5/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `save!'
	from /Users/alex.evanczuk/workspace/reproduce_papertrail_issue/reproduce.rb:95:in `<main>'
```

## Output with PaperTrail major version 5
```
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using json 1.8.6
Using minitest 5.10.3
Using thread_safe 0.3.6
Using builder 3.2.3
Using arel 6.0.4
Using bundler 1.15.4
Using byebug 9.1.0
Using coderay 1.1.2
Using method_source 0.9.0
Using request_store 1.3.2
Using sqlite3 1.3.13
Using i18n 0.9.1
Using tzinfo 1.2.4
Using pry 0.11.3
Using activesupport 4.2.7.1
Using pry-byebug 3.5.1
Using activemodel 4.2.7.1
Using activerecord 4.2.7.1
Using paper_trail 5.0.0
-- create_table(:super_user_details, {:force=>true})
   -> 0.0037s
-- create_table(:regular_user_details, {:force=>true})
   -> 0.0003s
-- create_table(:users, {:force=>true})
   -> 0.0112s
-- create_table(:versions)
   -> 0.0004s
-- add_index(:versions, [:item_type, :item_id])
   -> 0.0002s
-- add_index(:versions, [:transaction_id])
   -> 0.0005s
-- create_table(:version_associations)
   -> 0.0004s
-- add_index(:version_associations, [:version_id])
   -> 0.0003s
-- add_index(:version_associations, [:foreign_key_name, :foreign_key_id], {:name=>"index_version_associations_on_foreign_key"})
   -> 0.0003s
D, [2017-11-30T16:12:15.176872 #93450] DEBUG -- :    (0.0ms)  begin transaction
D, [2017-11-30T16:12:15.180431 #93450] DEBUG -- :   SQL (0.2ms)  INSERT INTO "regular_user_details" ("company_name") VALUES (?)  [["company_name", "Big Corp Inc."]]
D, [2017-11-30T16:12:15.195499 #93450] DEBUG -- :   SQL (0.1ms)  INSERT INTO "versions" ("event", "object_changes", "item_id", "item_type", "created_at") VALUES (?, ?, ?, ?, ?)  [["event", "create"], ["object_changes", "---\ncompany_name:\n- \n- Big Corp Inc.\nid:\n- \n- 1\n"], ["item_id", 1], ["item_type", "RegularUserDetails"], ["created_at", "2017-12-01 00:12:15.194900"]]
D, [2017-11-30T16:12:15.198881 #93450] DEBUG -- :   SQL (0.1ms)  UPDATE "versions" SET "transaction_id" = ? WHERE "versions"."id" = ?  [["transaction_id", 1], ["id", 1]]
D, [2017-11-30T16:12:15.199190 #93450] DEBUG -- :    (0.0ms)  commit transaction
D, [2017-11-30T16:12:15.205119 #93450] DEBUG -- :    (0.0ms)  begin transaction
D, [2017-11-30T16:12:15.205873 #93450] DEBUG -- :   SQL (0.1ms)  INSERT INTO "users" ("first_name", "user_detail_id", "user_detail_type") VALUES (?, ?, ?)  [["first_name", "Fred"], ["user_detail_id", 1], ["user_detail_type", "RegularUserDetails"]]
D, [2017-11-30T16:12:15.209919 #93450] DEBUG -- :   SQL (0.1ms)  INSERT INTO "versions" ("event", "object_changes", "item_id", "item_type", "created_at") VALUES (?, ?, ?, ?, ?)  [["event", "create"], ["object_changes", "---\nfirst_name:\n- \n- Fred\nuser_detail_id:\n- \n- 1\nuser_detail_type:\n- \n- RegularUserDetails\nid:\n- \n- 1\n"], ["item_id", 1], ["item_type", "User"], ["created_at", "2017-12-01 00:12:15.208990"]]
D, [2017-11-30T16:12:15.210749 #93450] DEBUG -- :   SQL (0.0ms)  UPDATE "versions" SET "transaction_id" = ? WHERE "versions"."id" = ?  [["transaction_id", 2], ["id", 2]]
D, [2017-11-30T16:12:15.211018 #93450] DEBUG -- :    (0.1ms)  commit transaction
D, [2017-11-30T16:12:15.211448 #93450] DEBUG -- :   SQL (0.1ms)  UPDATE "users" SET "level" = 'a' WHERE "users"."id" = ?  [["id", 1]]
#<User:0x00007fa19c91b398>
D, [2017-11-30T16:12:15.211622 #93450] DEBUG -- :    (0.0ms)  begin transaction
D, [2017-11-30T16:12:15.212206 #93450] DEBUG -- :   SQL (0.1ms)  UPDATE "users" SET "first_name" = ? WHERE "users"."id" = ?  [["first_name", "Other name"], ["id", 1]]
D, [2017-11-30T16:12:15.214124 #93450] DEBUG -- :   SQL (0.1ms)  INSERT INTO "versions" ("event", "object", "object_changes", "item_id", "item_type", "created_at") VALUES (?, ?, ?, ?, ?, ?)  [["event", "update"], ["object", "---\nid: 1\nfirst_name: Fred\nlevel: :a\nuser_detail_id: 1\nuser_detail_type: RegularUserDetails\n"], ["object_changes", "---\nfirst_name:\n- Fred\n- Other name\n"], ["item_id", 1], ["item_type", "User"], ["created_at", "2017-12-01 00:12:15.213728"]]
D, [2017-11-30T16:12:15.214722 #93450] DEBUG -- :   SQL (0.0ms)  UPDATE "versions" SET "transaction_id" = ? WHERE "versions"."id" = ?  [["transaction_id", 3], ["id", 3]]
D, [2017-11-30T16:12:15.214964 #93450] DEBUG -- :    (0.0ms)  commit transaction
```

**Comment by AlexEvanczuk** [comment]
I saved this too early -- I'm still editing the issue with more detail and potential solutions.

**Comment by jaredbeck** [comment]
> I have a model that has some attribute X. I also have that model delegate X to some other polymorphic model A. That model does not implement X in some cases.

Hi Alex. That's a pretty unusual situation. Have you tried `skip`ing that attribute?

```ruby
class User < ActiveRecord::Base
  has_paper_trail skip: [:level]
end
```

**Comment by AlexEvanczuk** [comment]
@jaredbeck 
That didn't fix it.  I've cloned the repo and am running `git bisect` between version 5 and version 7 and looking into what commit introduced the issue.

**Comment by AlexEvanczuk** [comment]
## Commit for 5.0.0.pre
```
commit 6862abd980e6cd0c3bcbe16c31209291309d402f (refs/bisect/good-6862abd980e6cd0c3bcbe16c31209291309d402f)
Author: Ben Atkins <batkinz@gmail.com>
Date:   Mon Jan 18 20:57:40 2016 -0500

    Bump version number to 5.0.0.pre [ci skip]
```

```
git bisect start HEAD 6862abd
git bisect run ruby ../reproduce.rb
```

```
ad5976ebc0ad3aecad19dc0a1967191df8078b17 is the first bad commit
```

@sgrif looks like this is your commit, would be great if you could help provide some context!
```
commit ad5976ebc0ad3aecad19dc0a1967191df8078b17
Author: Sean Griffin <sean@seantheprogrammer.com>
Date:   Wed Nov 30 12:10:59 2016 -0500

    Add support for Rails 5.1

    This updates the code to work with Rails 5.1.0.alpha, as of commit
    https://github.com/rails/rails/commit/1bdc395d956f789b6612796ac6f130cde90d3066.

    The biggest change was to call the new methods provided by
    `ActiveRecord::Dirty` when needed. In the next version of Rails after
    5.1, dirty will be "cleared" before after_save callbacks are run. This
    means that code in an after_save callback will behave the same as if it
    was run after calling `.save`.

    Since the concept of "changed" is fairly nebulous, two new method sets
    were introduced with names that specify whether they're operating on
    changes from what we think is in the database to what's in memory, or
    the changes that were just persisted. Paper trail will now use the
    latter set of methods if available and called from an after_ callback.

    There were a few other unrelated changes required to get this working on
    master. The first was the change from `appear_as_new_record` to
    `appear_as_unpersisted`. This was due to a single test that broke as a
    result of
    https://github.com/rails/rails/commit/c546a2b045600b6d700140adf2a4df666d6e08ce
    where reifying a version with a nil has_one association was persisting the
    change to the foreign key. I am actually unsure how that commit caused
    the problem (or more specifically, I'm unsure how it was passing
    before). However, as best as I can tell, the purpose of
    `appear_as_new_record` was to attempt to prevent the callbacks in
    `AutosaveAssociation` (which is the module responsible for persisting
    foreign key changes earlier than most people want most of the time
    because backwards compatibility or the maintainer hates himself or
    something) from running. By also stubbing out `persisted?` we can
    actually prevent those. A more stable option might be to use `suppress`
    instead, similar to the other branch in `reify_has_one`.

    The remaining breakage was due to the `Song` model relying on internals
    that have changed from underneath it. From Rails 5 onwards there is a
    public API available to do what it wants, so we can just use that
    instead.

    This commit is not expected to pass on Rails 3, as #898 makes it sound
    like support might be dropped. If this needs to be ammended to support
    Rails 3, I will do so, but I will also grumble very loudly about it.
```

**Comment by jaredbeck** [comment]
Can you reproduce this issue on the latest versions of PT and rails, currently 8.0.1 and 5.1.4?

**Comment by AlexEvanczuk** [comment]
It passes with those versions.

**Comment by jaredbeck** [comment]
> It passes with those versions.

Interesting. I actually didn't expect that. Well, we're getting ready to release PT 9 soon and rails 4.2 is out the door, so I'm not too interested in working on this myself, but if you find a fix I'll be happy to review a PR against the `7-stable` branch, and do a patch release.

**Comment by AlexEvanczuk** [comment]
I think you have good points here.  This is a pretty rare case where something that arguably makes no sense has to be done (having a column that is the same name as a delegated method name which is not implemented), we are running fine on 5, and at least blows up loudly rather than silently failing to save versions.

I currently I can't dedicate the time to a patch -- our team will wait until we upgrade to Rails 5 and then bump to PaperTrail 8 or 9 at that point.  Thanks for your responses.

Regards,
Alex

**Comment by jaredbeck** [comment]
> I currently I can't dedicate the time to a patch .. Thanks for your responses.

No problem.
