### ISSUE TITLE
Error in version 3.0.3

### ISSUE THREAD

**Issue by yvalenta** [airblade/paper_trail#403]
After upgrade paper_trail version from 3.0.2 to 3.0.3 i am getting this error
undefined method `timestamp_sort_order' for #Class:0x0000000425e3c0

The backtrace show me the following error in paper_trail gem ->
https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/has_paper_trail.rb#L70

what i am doing wrong?
