### ISSUE TITLE
Setting whodunnit in the rails console not work with rails 5.1.3

### ISSUE THREAD

**Issue by igortice** [airblade/paper_trail#982]
initializers/paper_trail.rb:8:in `<top (required)>': undefined method `application' for Rake:Module (NoMethodError)

**Comment by jaredbeck** [comment]
Thanks for the bug report. Per our [contributing guide][1] please use
our [bug report template][2]. If that's hard to use, please create a sample app that reproduces the problem. Thanks!

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by linstantnoodles** [comment]
I'm getting the same issue and it looks like it started happening > `5.0.4`. I'll put in specifics when I get a chance later today.

**Comment by linstantnoodles** [comment]
@jaredbeck The issue is reproduced while trying to start a rails server using `rails server` so I couldn't use a template. Here's a sample application that I made with two commits that demonstrate the issue: https://github.com/linstantnoodles/papertrail-rails-5-issue

**Versions**
Ruby version: `2.4.0`
Rails version: `5.1.3` 
Paper Trail version: `7.1.0`

The first commit are rails files are all freshly generated through the standard rails app create command `rails new myapp --database=postgresql`. Running the rails server works fine at this stage. The second commit involves adding paper_trail initializer code from the [wiki](https://github.com/airblade/paper_trail/wiki/Setting-whodunnit-in-the-rails-console) which causes the application to break on `rails server`. 

Steps to reproduce:

1. Close the repository
2. Run bundle install `bundle install` 
3. Run rails server `rails server`
4. Notice error ``<top (required)>': undefined method `application' for Rake:Module (NoMethodError)`

**Comment by jaredbeck** [comment]
I see, this is an issue with some code contributed to the wiki, specifically this page: https://github.com/airblade/paper_trail/wiki/Setting-whodunnit-in-the-rails-console

Code in the wiki isn't officially supported, but github doesn't provide a good place to discuss wiki pages, so I see no harm in using the issue tracker, if that's helpful to you.

I don't know much about it, but it looks like `Rake` isn't fully loaded yet during initializers. Specifically, `lib/rake/rake_module.rb` is not loaded yet. That's the file that defines `Rake.application`. So, I don't know what the solution is. Maybe you can add a `require "rake"` to the top of your initializer? But, I don't really understand the purpose of calling `Rake.application` in the first place. Maybe just don't call `Rake.application`?

**Comment by linstantnoodles** [comment]
@jaredbeck 

That's good to know, thank you! Just spoke to a teammate and it does sound like we don't need to be calling that. Not sure why it stopped working > 5.0.4 but in any case we should be good here. We'll go with your suggestion and just remove that call. 

Thanks!

**Comment by jaredbeck** [comment]
OK, I'll close this then. Please update the wiki with your findings.
