### ISSUE TITLE
ActsAsTaggableOn PaperTrail error

### ISSUE THREAD

**Issue by dankohn** [airblade/paper_trail#464]
I'm encountering a strange issue with 4.0.0beta1 that's not there with 3.0.6. When I run our complete cucumber tests, I get the error:
```
(::) failed steps (::)

undefined method `paper_trail_enabled_for_model?' for ActsAsTaggableOn::Taggable:Module (NoMethodError)
./app/controllers/application_controller.rb:35:in `update'
./app/controllers/application_controller.rb:73:in `use_zone'
./features/step_definitions/study_steps.rb:66:in `/^I save the Study$/'
features/studies.feature:18:in `And I save the Study'

Failing Scenarios:
cucumber features/studies.feature:9 # Scenario: Edit Existing Study
```
However, when I run just `cucumber features/studies.feature:9` it passes. Both work fine with 3.0.6. This is testing with Rails 4.1.9 and acts-as-taggable-on 3.4.3.

The failing step is simply:
```ruby
# study_steps.rb:66
When(/^I save the Study$/) do
  click_button 'Save'
end

# application_controller.rb:73
  def use_zone(&block)
    Time.use_zone(time_zone, &block)
  end
```

Thanks in advance for any suggestions.

**Comment by batter** [comment]
I'm guessing you have a model where you are inheriting from `ActsAsTaggableOn` and also versioning it w/ `PaperTrail`?  Perhaps #362 can help you, perhaps it's unrelated.

Here is what I can tell you: `paper_trail_enabled_for_model?` is available as a class method for ALL models. In PaperTrail `v3.x`, that method would always return `true` unless you had specifically turned it off for a specific model inside of your app. As you can see in the `CHANGELOG`, for PaperTrail `v4.x`, that method has now been made to be more intelligent, and will actually return `false` if `has_paper_trail` is not declared on a model.  See #438 for more on the update.

There is also an instance method which will only be available if `has_paper_trail` has been declared on a model.  The behavior for that one is the same as you would expect (returns `true` unless it has been turned off for that particular model).  It actually just [makes a call to the class level method](https://github.com/airblade/paper_trail/blob/v4.0.0.beta1/lib/paper_trail/has_paper_trail.rb#L226).

So it seems to me as though for some reason a call is being made to a model at the class-level when perhaps it shouldn't be...

The only other thing I can think of is that `v3.x`, the Cucumber helper is included by default, whereas w/ `v4.x` it must be manually required if you want to use it.  So if this is only failing in your tests, you may want to take a look at that.

**Comment by batter** [comment]
Also, I I just released `v4.0.0.beta2`, can you give that a try?

**Comment by dankohn** [comment]
`4.0.0.beta2` fixed my bug. Thanks very much!
